### ISSUE TITLE
Add the ability to select elements by their text

### ISSUE THREAD

**Issue by dkniffin** [site-prism/site_prism#42]
I would like to have the ability to select elements by the text they contain. For example:

```rb
class DummyPage < SitePrism::Page
  element :homepage_button, ".button", text: "Homepage"
end
```

This could be implemented using Capybara's `page.users_with_text`.

This same request was made in [an issue on the old repo](https://github.com/natritmeyer/site_prism/issues/10), but I'd like to revisit the decision not to implement this. That decision seems to have been made based on an opinion that selecting elements by text is bad. However, in my opinion, feature tests that use capybara and site_prism should test things as closely to the user's perspective as possible. User's do not know about CSS classes, ids, etc. All they see when they're viewing the page is the text and boxes and such. If I were to describe to a user how to navigate to something, I would not say "Click on the #button-homepage button" I would say "Click the button with the text "Homepage"". I would like to do the same in my feature tests.

This approach also has the advantage that it decouples the tests from the HTML structure a bit. If CSS classes or IDs change because of design or business decisions, but the button with that text is still on the page, the test does not break.

**Comment by luke-hill** [comment]
https://github.com/site-prism/site_prism/blob/master/features/support/pages/slow.rb#L11

This currently exists. The issue you relate to also mentions that it can be done but nat wasn't a fan of it.

Also remember that was with a Capybara version in the 1.x series from 2012. Capybara and all testing has moved on since then. We essentially pass the hashable query for locating the element to Capybara. So specifying text works.

**Comment by dkniffin** [comment]
🤦‍♂Wow. It's even documented in the readme! I'm sorry for wasting your time on this. I think I did a google search and that old issue was the first thing to come up.
