### ISSUE TITLE
[Feature request] - ViewComponent support

### ISSUE THREAD

**Issue by dkniffin** [site-prism/site_prism#69]
[ViewComponent](https://github.com/github/view_component) is a new library from Github that is gaining support quickly. It encapsulates views and partials into objects that can be easily rendered and tested. However, as far as I can tell, there is not a great way to use the Page Object Model and specifically site_prism with this awesome new tool.

In my head, I think the ideal way this would work is I would create a section class (inheriting from `SitePrism::Section`), then instantiate that with the html output coming from `render_inline(MyComponent.new(...)).to_html` from ViewComponent's helpers. Then I could interact with that in the same way I could any other section on a page. I could also reuse that section class in a feature test when I'm using a browser driver to interact with the page, getting double bang for my buck.

I'm not sure exactly what would be needed to make this work. Essentially I think I want to instantiate a `Section` without a `Page`, and without requiring capybara to pre-define a `page` object. I'm not sure if this requires any changes to site_prism or even capybara, or if I'm just missing how to do this with the current version of the library.

Any help with this is greatly appreciated!

**Comment by luke-hill** [comment]
So some things you need to be aware of

1) You can instantiate raw html just by doing `Capybara.string(html)` - This works as a page when doing `#load`
2) A Section "technically" doesn't need a page. If you mocked out and used doubles it would work. A Section has 3 initialize args. A `root_element` a `parent` and an optional block. Here the only important one is root_element, as this provides your scoping.

If you instantiated a Section and provided a nil arg for parent. Then `#parent_page` would throw an error. But as this is a rarely called method, pretty much everything else should work as intended.

It's worth pointing out instantiating a Section is pretty much entirely api private (I know we don't document it as such), so any issues you encounter there are unlikely to be fixed, unless you can show the fix is completely backwards compatible.

**Comment by dkniffin** [comment]
@luke-hill That's very helpful info. I'll give that a shot and see if it works. If it works well, maybe site_prism could consider some of those "private apis" public and I can write up some documentation on how this gem would be used with view_component.

**Comment by luke-hill** [comment]
They're only api private in the sense of they should not be initialized directly, but instead created through the usage of SitePrism in a normal manner. It wouldn't be something we would advise people to do, because then traits would not be passed down through inheritance (parent / page for example).

**Comment by dkniffin** [comment]
Alright, dug into this a little more and it works like you said:

```rb
html_string = render_inline(LabelComponent.new(args)).to_html # Render the html from my ViewComponent class
capybara_object = Capybara.string(render_inline(described_class.new(args)).to_html)
section = LabelComponentSection.new(nil, capybara_object)
section.text # This works as expected.
```

It looks like `Capybara.string` is a public method, so that's fine. The only thing that isn't 100% "kosher" here is the `LabelComponentSection.new`. Like you said, that's not exactly a private method, but from the SitePrism docs, it's not intended to be used directly. I think what I'll do is create a little helper method to do that step, so that if the API for that changes later, it'll be easy to swap out my implementation. Maybe that helper could make its way back into site_prism as an official API? Just something like:

```rb
def render_section(section_class, capybara_object)
  section_class.new(nil, capybara_object)
end
```

**Comment by luke-hill** [comment]
Do you mean like this? https://github.com/site-prism/site_prism/blob/master/lib/site_prism/dsl.rb#L142

**Comment by dkniffin** [comment]
Hmm. I guess that line, but wrapped in a publicly accessible API, documented in the readme. So it's an officially supported way to create a section by itself. Maybe even pull the `Capybara.string` call into it. So something like `SitePrism::Section.from_string(string)`

**Comment by luke-hill** [comment]
The problem is what your describing only works in a subset of situations. You are attempting to create a section without it "belonging" anywhere. I still don't get why you need to manually create a section without doing the DSL inline.

If you had a Page Object representing your page, just do `section :name_of_section, '.locator.of.section'`

I'm aware you're in a testing / mocking phase. But if you're looking to use SitePrism, you should have a basic concept of your page / section. So you should have as the bare minimum

Something representing your page (I think here you have an html fragment as a string)
Something representing your section (I think here you have a locator or something inside your html string)

If you want to submit a PR feel free. But I'm still not seeing what you can't do with the existing code. The only idea that I potentially have that would save a lot of time, is if you wanted the section "scoped" as the full page. i.e. your testing some small section which is the entire view (Like you would say on Storybook). In which case the `parent` would basically be non-infinite version of `self`. The best / quickest way to remedy this would be something like.

`SitePrism::Section.new(SitePrism::Page.new, locator_of_section)`

Consequently, a PR which "defaulted" the Section initializer to a new instance of page if a separate parent wasn't provided would be accepted, which would then leave you with your version being just.

`SitePrism::Section.new(locator_of_section)`- Which to me feels almost like what you're trying to achieve. But I might be wrong.

**Comment by dkniffin** [comment]
@luke-hill sorry for the confusion. What you describe with Storybook is close to what I'm looking to do here. You can think of ViewComponent as basically a different way to create a rails partial (eg `_label.html.erb` or `_label.html.slim`). I want to unit test that in isolation, without having to load up a whole page (and do the routing and controller and whatnot). What I'm describing could also be useful in testing rails partials in isolation, for example in a view spec (though I've not seen those used that often). 

One reason to do this vs a full-fledged feature test in Capybara is it adds the overhead/time of loading a headless browser, hitting the routes & middleware, and hitting the controller (which likely needs to have some setup or stubbing to get to a particular render state of the component being tested).

Now, I could test the html string manually, which is [essentially what the ViewComponent readme recommends](https://github.com/github/view_component#testing-1). But I like the SitePrism style of creating objects to represent pages and sections of pages, so that you can interact with them in an abstracted way. So, what I'd like is a way to turn that html partial string (output of the `render_inline` helper from ViewComponent, which is a subsection of the entire DOM `"<span class=\"label\">Some text</span>"`), into a SitePrism object. As stated above, this also has the benefit that when I use that component/partial on a page and test the entire page with a feature test, I can re-use the SitePrism object there as well, probably embedded in a `Page` object.

What you describe above "a basic concept of your page / section" makes sense. I could see creating a stubbed `Page` object as a wrapper around the component/partial/section being tested. But I want that process of creating the mocked page to be easy, with minimal boilerplate. 

As for what I can't do with the existing code, I think everything is there and I could start using a method-ized version of [that snippet I posted above](https://github.com/site-prism/site_prism/issues/69#issuecomment-665938847). Matter of fact, I've already created that in my codebase:

```rb
  # Renders a ViewComponent into a SitePrism::Section class
  def render_to_section(component, section_class, &block)
    html_string = render_inline(component, &block)
    capybara_object = Capybara.string(html_string)
    section_class.new(nil, capybara_object)
  end

  # usage
  render_to_section(LabelComponent.new({ type: "warn" }), LabelComponentSection) { "Some text" }
```

I'm just worried about calling the `SitePrism::Section.new` directly, without going through the DSL, because like you said, that's kinda a private API. Or at least it's not documented as something that should be used. So I'm worried that some refactor in the future might break my implementation. To avoid that, I'd like to move my method (or some variation of it) into the SitePrism codebase. 

This is basically what my PR would contain (though implemented in the actual code, rather than a monkeypatch):

```rb
module SitePrism
  class Section
    def self.from_view_component(component, &block)
      html_string = render_inline(component, &block).to_html
      capybara_object = Capybara.string(html_string)
      self.new(nil, capybara_object)
    end
  end
end

# usage
LabelComponentSection.from_view_component(LabelComponent.new({ type: "warn" })) { "Some text" }
```

or, if you want to remove the coupling to ViewComponent:
```rb
module SitePrism
  class Section
    def self.from_string(html_string)
      capybara_object = Capybara.string(html_string)
      self.new(nil, capybara_object)
    end
  end
end

# usage
html_string = render_inline(LabelComponent.new({ type: "warn" })) { "Some text" }
LabelComponentSection.from_view_component(html_string)
```

**Comment by luke-hill** [comment]
As mentioned we don't need to extend the public API, we can just default the Section to having the parent as a page entity. That's a tiny PR, but one which would probably go into a major release, as you would need to flip the argument assigns.

That then fixes all of your issues. As for calling Section initialization yourself. Again I would just use the DSL, and inside a page just call `section :name, locator` You can load a html page from a string by default using our API.

**Comment by luke-hill** [comment]
You can create a blank / semi blank site prism page, and then just pass in your capybara string to the load function, we handle the rest dynamically.

See https://github.com/site-prism/site_prism/blob/master/spec/site_prism/page_spec.rb#L109-L210 for more info - They cover a fair few use cases.

**Comment by luke-hill** [comment]
ping @dkniffin is there anything else needed commit wise here?

**Comment by dkniffin** [comment]
I haven't been working with ViewComponent in a bit for unrelated reasons. I think this is good-to-go for now, so I'll close this and if I run into issues again later, I'll ping again or open a new issue.
